#!/usr/bin/env python3
"""
Patch the official CRI CPK File Builder command line tool (cpkmakec.exe) so it can
pack and extract the FFBE JP CPK format.

The FFBE JP format stores every file of the CPK encrypted with a key derived from the
file's own name (see LibCPK/AssetCipher.cs). The official tool knows nothing about that, so the
patched cpkmakec.exe adds one option:

    --ffbejp        (also accepted: -ffbejp)

    Packing    cpkmakec <input dir or CSV> <output.cpk> [normal options] --ffbejp
               Every input file is encrypted (into a temporary copy, your files are not touched)
               and the official tool then builds the CPK from the encrypted copies.

    Extracting cpkmakec <input.cpk> -extract=<outdir> --ffbejp
               The official tool extracts the files, which are then decrypted in place.

Without --ffbejp the patched tool behaves exactly like the original (it simply starts it).

How the patch works: the original executable is kept next to the new one as
cpkmakec.original.exe and a small launcher, compiled here from the embedded C# source, takes its place
as cpkmakec.exe. Nothing inside the original binaries is modified.

Notes
  * Encrypted data does not compress, so --ffbejp can not be combined with -forcecompress or with
    compressed ("C") CSV entries. The original files of the FFBE JP CPKs are stored uncompressed.
  * -mode=ID packs no file names; the file name key can only be derived for modes that store names
    (FILENAME, FILENAMEID, FILENAMEGROUP, ...), when extracting as well.
  * Files whose name contains "unit_unit1" are not encrypted, like in the original game data.

Usage
    python patch_official_cpkmaker.py <folder containing cpkmakec.exe>
    python patch_official_cpkmaker.py <folder containing cpkmakec.exe> --restore

A C# compiler is required for patching. On Windows the one shipped with the .NET Framework
(C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\csc.exe) is found automatically, it is the
same framework the official tool needs. Elsewhere csc or mcs from PATH is used, or pass --compiler.
"""

import argparse
import glob
import os
import shutil
import subprocess
import sys
import tempfile

TOOL_NAME = "cpkmakec.exe"
ORIGINAL_NAME = "cpkmakec.original.exe"

LAUNCHER_SOURCE = r'''
// ---- FFBEJP_CPKMAKEC_LAUNCHER (generated by patch_official_cpkmaker.py) ----
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;

namespace FfbeJpLauncher
{
    internal static class AssetCipher
    {
        public static bool AppliesTo(string fileName)
        {
            return fileName != null && !fileName.Contains("unit_unit1");
        }

        private static uint KeyHash(string fileName)
        {
            byte[] key = Encoding.ASCII.GetBytes(fileName);
            uint hash = 0;
            for (int i = 0; i < key.Length && key[i] != 0; i++)
            {
                hash = unchecked(hash * 31 + key[i]);
            }
            return hash;
        }

        private static byte KeyByte(uint hash, int index)
        {
            return unchecked((byte)(((hash >> (8 * (index & 3))) & 0xFF) + (index % 255)));
        }

        public static byte[] Decrypt(byte[] data, string fileName)
        {
            if (!AppliesTo(fileName)) return data;
            byte[] r = (byte[])data.Clone();
            uint hash = KeyHash(fileName);
            int half = r.Length >> 1;
            int second = half + (r.Length & 1);
            for (int i = 0; i < half; i++)
            {
                byte k = KeyByte(hash, i);
                byte a = r[i];
                byte b = r[second + i];
                r[i] = (byte)(k ^ b);
                r[second + i] = (byte)(a ^ ~k);
            }
            return r;
        }

        public static byte[] Encrypt(byte[] data, string fileName)
        {
            if (!AppliesTo(fileName)) return data;
            byte[] r = (byte[])data.Clone();
            uint hash = KeyHash(fileName);
            int half = r.Length >> 1;
            int second = half + (r.Length & 1);
            for (int i = 0; i < half; i++)
            {
                byte k = KeyByte(hash, i);
                byte p1 = r[i];
                byte p2 = r[second + i];
                r[i] = (byte)(p2 ^ ~k);
                r[second + i] = (byte)(p1 ^ k);
            }
            return r;
        }
    }

    internal class LauncherException : Exception
    {
        public LauncherException(string message) : base(message) { }
    }

    internal static class Program
    {
        private static readonly string[] PathOptions = { "attralign", "addrange", "header", "cpkproj", "logsort" };

        private static bool IsFfbeJpFlag(string arg)
        {
            string a = arg.ToLowerInvariant();
            return a == "--ffbejp" || a == "-ffbejp";
        }

        private static string OptionName(string arg)
        {
            if (arg.Length < 2 || arg[0] != '-') return null;
            int eq = arg.IndexOf('=');
            string name = eq < 0 ? arg.Substring(1) : arg.Substring(1, eq - 1);
            return name.ToLowerInvariant();
        }

        private static string OptionValue(string arg)
        {
            int eq = arg.IndexOf('=');
            return eq < 0 ? null : arg.Substring(eq + 1).Trim('"');
        }

        private static void Info(string text)
        {
            Console.WriteLine("[ffbejp] " + text);
        }

        private static int Main(string[] args)
        {
            string dir = AppDomain.CurrentDomain.BaseDirectory;
            string original = Path.Combine(dir, "cpkmakec.original.exe");
            if (!File.Exists(original))
            {
                Console.WriteLine("Error : cpkmakec.original.exe not found next to the launcher.");
                return 1;
            }

            bool ffbejp = false;
            List<string> rest = new List<string>();
            foreach (string a in args)
            {
                if (IsFfbeJpFlag(a)) ffbejp = true; else rest.Add(a);
            }

            if (!ffbejp)
            {
                int code = Run(original, rest, null);
                if (args.Length == 0) PrintUsage();
                return code;
            }

            string tempDir = null;
            try
            {
                string extractDir = null;
                List<string> positional = new List<string>();
                foreach (string a in rest)
                {
                    string name = OptionName(a);
                    if (name == null) { positional.Add(a); continue; }
                    if (name == "extract") extractDir = OptionValue(a);
                    if (name == "forcecompress") throw new LauncherException("--ffbejp can not be combined with -forcecompress (encrypted data does not compress).");
                    if (name == "verify" || name == "view") throw new LauncherException("--ffbejp can not be combined with -" + name + ".");
                }

                if (extractDir != null)
                {
                    if (positional.Count < 1) throw new LauncherException("less arguments.");
                    int code = Run(original, rest, null);
                    if (code == 0)
                    {
                        DecryptTree(Path.GetFullPath(extractDir));
                    }
                    return code;
                }

                if (positional.Count < 2) throw new LauncherException("less arguments.");

                tempDir = Path.Combine(Path.GetTempPath(), "ffbejp_" + Guid.NewGuid().ToString("N"));
                Directory.CreateDirectory(tempDir);

                string input = positional[0];
                string workDir = null;
                List<string> newArgs = new List<string>();

                if (Directory.Exists(input))
                {
                    string encrypted = Path.Combine(tempDir, "data");
                    Info("Encrypting " + CountAndEncryptTree(Path.GetFullPath(input), encrypted) + " file(s) ...");
                    newArgs = ReplaceFirstPositional(rest, positional[0], encrypted);
                    newArgs = AbsolutizePaths(newArgs);
                    newArgs = AbsolutizeOutput(newArgs, positional[1]);
                }
                else if (File.Exists(input))
                {
                    workDir = Path.Combine(tempDir, "csv");
                    Directory.CreateDirectory(workDir);
                    string newCsv = EncryptCsv(Path.GetFullPath(input), workDir, rest);
                    newArgs = ReplaceFirstPositional(rest, positional[0], newCsv);
                    newArgs = AbsolutizePaths(newArgs);
                    newArgs = AbsolutizeOutput(newArgs, positional[1]);
                }
                else
                {
                    throw new LauncherException(input + " is not found.");
                }

                return Run(original, newArgs, workDir);
            }
            catch (LauncherException ex)
            {
                Console.WriteLine("Error : " + ex.Message);
                return 1;
            }
            finally
            {
                if (tempDir != null)
                {
                    try { Directory.Delete(tempDir, true); } catch (Exception) { }
                }
            }
        }

        private static List<string> ReplaceFirstPositional(List<string> list, string oldValue, string newValue)
        {
            List<string> result = new List<string>();
            bool done = false;
            foreach (string a in list)
            {
                if (!done && a == oldValue && OptionName(a) == null)
                {
                    result.Add(newValue);
                    done = true;
                }
                else
                {
                    result.Add(a);
                }
            }
            return result;
        }

        // The csv mode runs in a temporary working directory, so every path the user gave must be absolute.
        private static List<string> AbsolutizePaths(List<string> list)
        {
            List<string> result = new List<string>();
            foreach (string a in list)
            {
                string name = OptionName(a);
                string value = OptionValue(a);
                if (name != null && value != null && Array.IndexOf(PathOptions, name) >= 0)
                {
                    result.Add("-" + name + "=" + Path.GetFullPath(value));
                }
                else
                {
                    result.Add(a);
                }
            }
            return result;
        }

        private static List<string> AbsolutizeOutput(List<string> list, string output)
        {
            List<string> result = new List<string>();
            bool done = false;
            string full = Path.GetFullPath(output);
            foreach (string a in list)
            {
                if (!done && a == output && OptionName(a) == null)
                {
                    result.Add(full);
                    done = true;
                }
                else
                {
                    result.Add(a);
                }
            }
            return result;
        }

        private static int CountAndEncryptTree(string source, string target)
        {
            int count = 0;
            foreach (string file in Directory.GetFiles(source, "*", SearchOption.AllDirectories))
            {
                string relative = file.Substring(source.Length).TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
                string dest = Path.Combine(target, relative);
                Directory.CreateDirectory(Path.GetDirectoryName(dest));
                File.WriteAllBytes(dest, AssetCipher.Encrypt(File.ReadAllBytes(file), Path.GetFileName(file)));
                count++;
            }
            return count;
        }

        private static void DecryptTree(string dir)
        {
            if (!Directory.Exists(dir))
            {
                Info("Output directory " + dir + " not found, nothing to decrypt.");
                return;
            }

            int count = 0;
            foreach (string file in Directory.GetFiles(dir, "*", SearchOption.AllDirectories))
            {
                string name = Path.GetFileName(file);
                if (!AssetCipher.AppliesTo(name)) continue;
                byte[] data = AssetCipher.Decrypt(File.ReadAllBytes(file), name);
                if (data.Length >= 8 && Encoding.ASCII.GetString(data, 0, 8) == "CRILAYLA")
                {
                    Info("Warning: " + name + " is CRILAYLA compressed, it is decrypted but still compressed.");
                }
                File.WriteAllBytes(file, data);
                count++;
            }
            Info("Decrypted " + count + " file(s).");
        }

        private static Encoding CsvEncoding(List<string> args)
        {
            foreach (string a in args)
            {
                if (OptionName(a) == "code")
                {
                    string v = (OptionValue(a) ?? "").ToUpperInvariant();
                    if (v == "EUC") return Encoding.GetEncoding(51932);
                    if (v == "UTF-8" || v == "UTF8") return new UTF8Encoding(false);
                }
            }
            return Encoding.GetEncoding(932);
        }

        private static List<string> SplitCsv(string line)
        {
            List<string> fields = new List<string>();
            StringBuilder sb = new StringBuilder();
            bool quoted = false;
            foreach (char c in line)
            {
                if (c == '"') quoted = !quoted;
                if (c == ',' && !quoted)
                {
                    fields.Add(sb.ToString());
                    sb.Length = 0;
                }
                else
                {
                    sb.Append(c);
                }
            }
            fields.Add(sb.ToString());
            return fields;
        }

        // Encrypts the local files listed in the csv file. The encrypted copies keep the relative path
        // of the original so the contents names are unchanged.
        private static string EncryptCsv(string csvPath, string workDir, List<string> args)
        {
            Encoding enc = CsvEncoding(args);
            string csvDir = Path.GetDirectoryName(csvPath);
            string[] lines = File.ReadAllLines(csvPath, enc);
            List<string> output = new List<string>();
            int count = 0;

            for (int n = 0; n < lines.Length; n++)
            {
                string line = lines[n];
                List<string> f = SplitCsv(line);
                string local = f[0].Trim().Trim('"');
                if (local.Length == 0 || local.StartsWith("#") || local.StartsWith("//"))
                {
                    output.Add(line);
                    continue;
                }

                string contents = f.Count > 1 ? f[1].Trim().Trim('"') : "";
                string compress = f.Count > 3 ? f[3].Trim().ToUpperInvariant() : "";
                if (compress == "C" || compress == "COMP" || compress == "COMPRESS")
                {
                    throw new LauncherException("csv line " + (n + 1) + ": compressed entries can not be used with --ffbejp.");
                }

                string source = Path.IsPathRooted(local) ? local : Path.Combine(csvDir, local);
                if (!File.Exists(source)) source = Path.GetFullPath(local);
                if (!File.Exists(source))
                {
                    output.Add(line);   // let the official tool report the missing file
                    continue;
                }

                string newLocal;
                if (Path.IsPathRooted(local))
                {
                    if (contents.Length == 0)
                    {
                        throw new LauncherException("csv line " + (n + 1) + ": a local file with an absolute path needs a contents name when using --ffbejp.");
                    }
                    newLocal = Path.Combine("_abs", n.ToString(), Path.GetFileName(local));
                }
                else
                {
                    newLocal = local;
                }

                string keyName = Path.GetFileName((contents.Length > 0 ? contents : local).Replace('\\', '/'));
                string dest = Path.Combine(workDir, newLocal);
                Directory.CreateDirectory(Path.GetDirectoryName(dest));
                File.WriteAllBytes(dest, AssetCipher.Encrypt(File.ReadAllBytes(source), keyName));
                count++;

                f[0] = newLocal;
                output.Add(string.Join(",", f.ToArray()));
            }

            Info("Encrypted " + count + " file(s) of the csv.");
            string newCsv = Path.Combine(workDir, Path.GetFileName(csvPath));
            File.WriteAllLines(newCsv, output.ToArray(), enc);
            return newCsv;
        }

        private static string Quote(string arg)
        {
            if (arg.Length > 0 && arg.IndexOfAny(new char[] { ' ', '\t', '"' }) < 0) return arg;
            StringBuilder sb = new StringBuilder("\"");
            int backslashes = 0;
            foreach (char c in arg)
            {
                if (c == '\\')
                {
                    backslashes++;
                }
                else if (c == '"')
                {
                    sb.Append('\\', backslashes * 2 + 1);
                    sb.Append('"');
                    backslashes = 0;
                }
                else
                {
                    sb.Append('\\', backslashes);
                    sb.Append(c);
                    backslashes = 0;
                }
            }
            sb.Append('\\', backslashes * 2);
            sb.Append('"');
            return sb.ToString();
        }

        private static int Run(string exe, List<string> args, string workDir)
        {
            List<string> quoted = new List<string>();
            foreach (string a in args) quoted.Add(Quote(a));

            ProcessStartInfo psi = new ProcessStartInfo();
            bool windows = Environment.OSVersion.Platform == PlatformID.Win32NT;
            if (windows)
            {
                psi.FileName = exe;
                psi.Arguments = string.Join(" ", quoted.ToArray());
            }
            else
            {
                psi.FileName = "mono";
                psi.Arguments = Quote(exe) + " " + string.Join(" ", quoted.ToArray());
            }
            psi.UseShellExecute = false;
            if (workDir != null) psi.WorkingDirectory = workDir;

            using (Process p = Process.Start(psi))
            {
                p.WaitForExit();
                return p.ExitCode;
            }
        }

        private static void PrintUsage()
        {
            Console.WriteLine("");
            Console.WriteLine("[FFBE JP option]");
            Console.WriteLine("  --ffbejp                  : FFBE JP CPK format (every file is encrypted with a key derived from its name).");
            Console.WriteLine("                              Pack   : cpkmakec <Input CSV File or Directory> <Output CPK File> [Option] --ffbejp");
            Console.WriteLine("                              Extract: cpkmakec <Input CPK File> -extract=[outdir] --ffbejp");
        }
    }
}
'''


def find_compiler(explicit):
    if explicit:
        return explicit
    env = os.environ.get("CSC")
    if env:
        return env
    windir = os.environ.get("WINDIR") or os.environ.get("SystemRoot")
    if windir:
        for sub in ("Framework", "Framework64"):
            for path in sorted(glob.glob(os.path.join(windir, "Microsoft.NET", sub, "v4*", "csc.exe")), reverse=True):
                return path
    for name in ("csc", "csc.exe", "mcs"):
        found = shutil.which(name)
        if found:
            return found
    return None


def compile_launcher(compiler, out_path):
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "launcher.cs")
        with open(src, "w", encoding="utf-8") as f:
            f.write(LAUNCHER_SOURCE)
        # The official tool is a 32 bit process, keep the launcher the same.
        cmd = [compiler, "-nologo", "-target:exe", "-platform:x86", "-out:" + out_path, "-r:System.dll", src]
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
        if result.returncode != 0:
            raise SystemExit("Compiling the launcher failed:\n" + result.stdout)


def is_patched(path):
    with open(path, "rb") as f:
        return b"FfbeJpLauncher" in f.read()


def main():
    parser = argparse.ArgumentParser(description="Add --ffbejp (FFBE JP CPK format) support to the official cpkmakec.exe")
    parser.add_argument("tool", help="folder containing cpkmakec.exe (or the path of cpkmakec.exe)")
    parser.add_argument("--restore", action="store_true", help="put the original cpkmakec.exe back")
    parser.add_argument("--compiler", help="path of csc.exe / mcs used to build the launcher")
    opts = parser.parse_args()

    folder = opts.tool
    if os.path.isfile(folder):
        folder = os.path.dirname(os.path.abspath(folder))
    tool = os.path.join(folder, TOOL_NAME)
    original = os.path.join(folder, ORIGINAL_NAME)

    if opts.restore:
        if not os.path.exists(original):
            raise SystemExit(ORIGINAL_NAME + " not found, nothing to restore.")
        shutil.copyfile(original, tool)
        os.remove(original)
        print("Restored the original " + TOOL_NAME)
        return

    if not os.path.exists(tool):
        raise SystemExit(TOOL_NAME + " not found in " + folder)

    if os.path.exists(original):
        print(ORIGINAL_NAME + " already exists, keeping it as the original tool.")
    else:
        if is_patched(tool):
            raise SystemExit(TOOL_NAME + " is already patched but " + ORIGINAL_NAME + " is missing.")
        shutil.copyfile(tool, original)
        print("Saved the original tool as " + ORIGINAL_NAME)

    compiler = find_compiler(opts.compiler)
    if not compiler:
        raise SystemExit("No C# compiler found. Install the .NET Framework 4 (csc.exe) or pass --compiler.")

    compile_launcher(compiler, tool)
    print("Patched " + tool)
    print("New option: --ffbejp   (pack: cpkmakec <dir|csv> <out.cpk> [options] --ffbejp, extract: cpkmakec <in.cpk> -extract=<dir> --ffbejp)")


if __name__ == "__main__":
    main()
